---
- name: Ensure /opt/Todo-app directory exists
  become: yes
  file:
    path: /opt/Todo-app
    state: directory
    mode: '0755'

- name: Remove old frontend directory if it exists
  become: yes
  file:
    path: /opt/Todo-app/Todo-Frontend
    state: absent

- name: Copy the frontend source code to EC2
  become: yes
  copy:
    src: ../Todo-Frontend/
    dest: /opt/Todo-app/Todo-Frontend
    owner: root
    group: root
    mode: '0755'

- name: Install frontend dependencies
  become: yes
  npm:
    path: /opt/Todo-app/Todo-Frontend
    state: present

- name: Build frontend
  become: yes
  command: npm run build
  args:
    chdir: /opt/Todo-app/Todo-Frontend
