---
- name: Install frontend dependencies
  become: yes
  npm:
    path: /opt/todo-app/todo-frontend
    state: present

- name: Build frontend
  become: yes
  command: npm run build
  args:
    chdir: /opt/todo-app/todo-frontend
  