- name: Ensure the /opt directory exists
  become: yes
  file:
    path: /opt
    state: directory
    mode: '0755'

- name: Remove old todo-app directory if it exists
  become: yes
  file:
    path: /opt/todo-app
    state: absent

- name: Clone the Todo-App repository cleanly
  become: yes
  ansible.builtin.git:
    repo: "https://github.com/amitpandey8834/Todo-App.git"
    dest: /opt/todo-app
    version: main
    force: yes

- name: Install backend dependencies
  become: yes
  npm:
    path: /opt/todo-app/Todo-Backend
    state: present

- name: Install PM2 globally
  become: yes
  npm:
    name: pm2
    global: yes

- name: Check if start.js exists
  stat:
    path: /opt/todo-app/Todo-Backend/start.js
  register: start_js

- name: Debugging start.js existence
  debug:
    msg: "Start.js status: {{ start_js.stat.exists }}"

- name: Check the PM2 list
  become: yes
  command: pm2 list
  register: pm2_list
  changed_when: false

- name: Debug the PM2 list
  debug:
    var: pm2_list

- name: Start or restart the backend with pm2
  become: yes
  command: "pm2 start -f start.js"
  args:
    chdir: /opt/todo-app/Todo-Backend
  when: start_js.stat.exists

- name: Set pm2 to start on boot
  become: yes
  command: pm2 startup
  args:
    chdir: /opt/todo-app/Todo-Backend
